name: Build ThunderLibraries on Linux

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Linux build template.yml@development/actions-ubuntu-latest

  ThunderLibraries:
    needs: Thunder
    uses: WebPlatformForEmbedded/ThunderLibraries/.github/workflows/Linux build template.yml@main
