name: Build ThunderLibraries on Linux

on:
  push:
    # branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Linux build template.yml@development/actions-checkouts

  ThunderLibraries:
    needs: Thunder
    uses: WebPlatformForEmbedded/ThunderLibraries/.github/workflows/Linux build template.yml@development/actions-checkouts # change back to main
